### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sitaralove**
@pdxchance hoping this works?

### CODE REVIEW

**Comment by pdxchance** [comment]
I think you need to make me a reviewer for this PR If you look in the upper right hand corner under Reviewers, it says no reviewers. Do I have access to this repo?

**Comment by pdxchance** [comment]
Almost there. I have access to the repo now. But to review and comment on your PR, I will need to be added a a reviewer. Look in the upper right hand corner of your screen where it says reviewers. 

image

**Comment by Sitaralove** [comment]
I couldn't figure out how to just add a reviewer with adding you as a collaborator. You should have a request now...

The Pull request was to review the few games I found that fit your brief description. Let me know if you think I should keep looking. 

I was limited to what was in their 'Read Me' section and leaned towards those with graphics included. The other games with just dumped folders of code, I did not know what I was looking at. So may be some other good options out there I just need to figure out how to run these codes to try the games. If that makes sense?

**Review by pdxchance — CHANGES_REQUESTED** [review]
Looking good so far!!!! Let's take this farther. How can we make this READ.ME look a little tidier? 
Hint:
https://guides.github.com/features/mastering-markdown/

Also, will this serve as your public repo for this project? If so, I don't think it should mention pdxchance or what we are going to review together.  (Although we definitely can together). Maybe keep it a little more generic?

**Review by Sitaralove — COMMENTED** [review]
update to make more generic, not referencing reviewers

**Pull request merged**
