### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by pdxchance**
I think this is what you want? If you look at the master branch now the readme is blank. In your other PR you had a merge conflict which I don't think was resolved properly. Are these the changes you want?

### CODE REVIEW

**Comment by pdxchance** [comment]
Just a tip. You really don't ever want to change master directly. Rather, we branch from it. Make our changes. Get approval and then merge back to master.

**Comment by Sitaralove** [comment]
@pdxchance Yea I messed that up... I realised that only after, and then I was trying to resolve a conflict so I just deleting everything 👎 My bad. I will wait to get your review comments first. Not sure how to fix the branch conflict now. I have updated the Master. Should I start a new branch and get your to review the changes that way?

**Comment by pdxchance** [comment]
> @pdxchance Yea I messed that up... I realised that only after, and then I was trying to resolve a conflict so I just deleting everything 👎 My bad. I will wait to get your review comments first. Not sure how to fix the branch conflict now. I have updated the Master. Should I start a new branch and get your to review the changes that way?

Lets talk about it at mentoring. It seems master is up to date so we won't need this PR.

**Comment by pdxchance** [comment]
Closing this PR, master is up to date.

**Comment by Sitaralove** [comment]
Ok, great. Speak soon!

**Review by Sitaralove — COMMENTED** [review]
Just testing this.

**Pull request closed without merging**
